<?php

namespace AppBundle\Repository;

/**
 * SigninRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SigninRepository extends \Doctrine\ORM\EntityRepository
{
}
